### ISSUE TITLE
checkboxes & radio buttons styling

### ISSUE THREAD

**Issue by roefem** [OnroerendErfgoed/pyoes#235]
De default styling voor checkbox-custom en radio-custom aanpassen zodat de checks wit zijn:
![image](https://user-images.githubusercontent.com/62388265/159691170-01bfb6ad-2549-4162-85ea-549f7cff3716.png)
![image](https://user-images.githubusercontent.com/62388265/159691332-a77fd5e3-1be1-4669-a6a9-b794bcc94c9f.png)

```css
/* checks in custom radio buttons en checkboxes zijn default grijs */
.checkbox-custom + .checkbox-custom-label:before, .radio-custom + .radio-custom-label:before {
  font-family: "FontAwesome";
}

.radio-custom:checked + .radio-custom-label:before, .checkbox-custom:checked + .checkbox-custom-label:before {
  color: white ;
  content: "\f00c" ;
  font-size: 14px ;
  padding: 0 ;
  line-height: 20px;
}
```
